	UPDATE [dbo].[Usr_Personas]
	SET
	CodCorrPer = 1662,
    DocIde = '5061218',
    DocIdeExp = 'OR',
    Paterno = 'LAZO',
    Materno = 'VEGA',
    Conyuge = '',
    Nombres = 'NADIR DANITZA',
    Telefono = '',
    Sexo = 'F',
    FechNac = '1990-08-24',
    CodNivIns = 4,
    CodProf = 2,
    Cargo = 'OFICIAL',
    CodSuTrabContrA = 6,
    AreaTrabajo = 'GNRH',
    Observaciones = '',
    CodEntidad = 174,
    Direccion = '',
    CodDepto = 0,
    Celular = '70115237',
    CorreoElectronico = 'nadir_lazo@contraloria.gob.bo',
    EstadoCivil = 'S',
    CodNac = 2,
    LugarNacimiento = 'ORURO',
    UM_CodCorrPer = 654,
    UM_Fecha = GETDATE(),
    EsHistorico = 'N'
	WHERE CodCorrPer = 1662 AND DocIdeExp = 'ORU'
 